"""Yeni migration mesajı

Revision ID: 061bff6fa6b5
Revises: c3d6d2a22b5e
Create Date: 2026-02-27 11:37:11.274448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061bff6fa6b5'
down_revision: Union[str, Sequence[str], None] = 'c3d6d2a22b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cografya_Kutuphanesi', sa.Column('Plaka_numarasi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cografya_Kutuphanesi', 'Plaka_numarasi')
    # ### end Alembic commands ###
