"""Yeni migration mesajı

Revision ID: 4bc4d984f6cf
Revises: fd1dc99be0e8
Create Date: 2026-03-03 11:52:14.381441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc4d984f6cf'
down_revision: Union[str, Sequence[str], None] = 'fd1dc99be0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__Aday_Sonu__Secim__52593CB8'), 'Aday_Sonuclar_Tablosu', type_='foreignkey')
    op.create_foreign_key(None, 'Aday_Sonuclar_Tablosu', 'Secimler', ['Secim_ID'], ['ID'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__Parti_Son__Secim__5812160E'), 'Parti_Sonuclari_Tablosu', type_='foreignkey')
    op.create_foreign_key(None, 'Parti_Sonuclari_Tablosu', 'Secimler', ['Secim_ID'], ['ID'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__Secim_Gen__Secim__619B8048'), 'Secim_Genel_Bilgiler', type_='foreignkey')
    op.create_foreign_key(None, 'Secim_Genel_Bilgiler', 'Secimler', ['Secim_ID'], ['ID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Secim_Genel_Bilgiler', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Secim_Gen__Secim__619B8048'), 'Secim_Genel_Bilgiler', 'Secimler', ['Secim_ID'], ['ID'])
    op.drop_constraint(None, 'Parti_Sonuclari_Tablosu', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Parti_Son__Secim__5812160E'), 'Parti_Sonuclari_Tablosu', 'Secimler', ['Secim_ID'], ['ID'])
    op.drop_constraint(None, 'Aday_Sonuclar_Tablosu', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Aday_Sonu__Secim__52593CB8'), 'Aday_Sonuclar_Tablosu', 'Secimler', ['Secim_ID'], ['ID'])
    # ### end Alembic commands ###
