"""Yeni migration mesajı

Revision ID: 64924b4c8406
Revises: a6b2066fc6be
Create Date: 2026-02-26 13:38:26.048329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64924b4c8406'
down_revision: Union[str, Sequence[str], None] = 'a6b2066fc6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Sayisi',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('Secim_Genel_Bilgiler', 'Kayitli_Secmen_Sayisi',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Secim_Genel_Bilgiler', 'Oy_Kullanan_Secmen_Sayisi',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Secim_Genel_Bilgiler', 'Gecerli_Oy_Sayisi',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Secim_Genel_Bilgiler', 'Gecerli_Oy_Sayisi',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    op.alter_column('Secim_Genel_Bilgiler', 'Oy_Kullanan_Secmen_Sayisi',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    op.alter_column('Secim_Genel_Bilgiler', 'Kayitli_Secmen_Sayisi',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    op.alter_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Sayisi',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
