"""Yeni migration mesajı

Revision ID: 6889287fcff3
Revises: b00ab1399d04
Create Date: 2026-03-03 13:19:43.639706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6889287fcff3'
down_revision: Union[str, Sequence[str], None] = 'b00ab1399d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Aday_Sonuclar_Tablosu', sa.Column('Aday_Oy_Sayisi', sa.Integer(), nullable=True))
    op.add_column('Aday_Sonuclar_Tablosu', sa.Column('Aday_Oy_Orani', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Aday_Sonuclar_Tablosu', 'Aday_Oy_Orani')
    op.drop_column('Aday_Sonuclar_Tablosu', 'Aday_Oy_Sayisi')
    # ### end Alembic commands ###
