"""Oy sayisi ve oy oranlari eklenmiştirı

Revision ID: a6b2066fc6be
Revises: f7e1408072aa
Create Date: 2026-02-26 12:32:13.601938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b2066fc6be'
down_revision: Union[str, Sequence[str], None] = 'f7e1408072aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parti_Sonuclari_Tablosu', sa.Column('Parti_Oy_Sayisi', sa.Integer(), nullable=True))
    op.add_column('Parti_Sonuclari_Tablosu', sa.Column('Parti_Oy_Orani', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Orani')
    op.drop_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Sayisi')
    # ### end Alembic commands ###
