"""Yeni migration mesajı

Revision ID: b00ab1399d04
Revises: 4bc4d984f6cf
Create Date: 2026-03-03 13:18:11.351768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00ab1399d04'
down_revision: Union[str, Sequence[str], None] = '4bc4d984f6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__Aday_Sonu__Parti__5441852A'), 'Aday_Sonuclar_Tablosu', type_='foreignkey')
    op.drop_column('Aday_Sonuclar_Tablosu', 'Parti_ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Aday_Sonuclar_Tablosu', sa.Column('Parti_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__Aday_Sonu__Parti__5441852A'), 'Aday_Sonuclar_Tablosu', 'Partiler', ['Parti_ID'], ['ID'])
    # ### end Alembic commands ###
