"""Yeni migration mesajı

Revision ID: b848d6433e11
Revises: 64924b4c8406
Create Date: 2026-02-26 13:52:16.537185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b848d6433e11'
down_revision: Union[str, Sequence[str], None] = '64924b4c8406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cografya_Kutuphanesi', sa.Column('Tanım', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cografya_Kutuphanesi', 'Tanım')
    # ### end Alembic commands ###
