"""Yeni migration mesajı

Revision ID: c3d6d2a22b5e
Revises: b848d6433e11
Create Date: 2026-02-26 14:18:56.774664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d6d2a22b5e'
down_revision: Union[str, Sequence[str], None] = 'b848d6433e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Sayisi',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Parti_Sonuclari_Tablosu', 'Parti_Oy_Sayisi',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
