"""Yeni migration mesajı

Revision ID: f7e1408072aa
Revises: 
Create Date: 2026-02-25 16:14:40.503476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e1408072aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parti_Sonuclari_Tablosu', sa.Column('varsayilan_yaratilma_tarihi', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Parti_Sonuclari_Tablosu', 'varsayilan_yaratilma_tarihi')
    # ### end Alembic commands ###
